### ISSUE TITLE
Requirements for GPUs

### ISSUE THREAD

**Issue by zhengyuan-xie** [nickjiang2378/vl-interp#1]
Thanks for your great work! I tried to run internal_confidence.ipynb with llava-v1.5-7b on a single RTX 3090(24G) and got CUDA out of memory. I wonder requirements for GPUs to run the code. Looking for your reply.

**Comment by nickjiang2378** [comment]
We used RTX 6000 (50G) for all our experiments. I'm a little surprised it doesn't work for the 3090 though because llava7b on my machine takes up around 16GB. Did you pass in your device to the load_llava_state function? If you try the "run_llava.py" demo, do you run into similar issues? It exposes the underlying model generation calls, so maybe you can specify a lower precision.

**Comment by zhengyuan-xie** [comment]
Thanks for your fast reply. I directly clone this repo, set os.environ['CUDA_VISIBLE_DEVICES'] = '0' and replace the path in llava_utils.py with my local path, so I think the device is correctly passed to the load_llava_state function (I print vocab_embeddings in load_llava_state and it was loaded on cuda:0). I also try run_llava.py, it runs successfully but the memory usage also reached about 23G. I will try to use an 8-bit model later.

**Comment by nickjiang2378** [comment]
Gotcha. Until I figure out how to reduce the memory footprint, I'd recommend upgrading GPUs. Are you looking to try out anything specific with model confidences?

**Comment by zhengyuan-xie** [comment]
Thanks for the suggestion. I ran the code on an A40 GPU (46G) and got the same issue. Maybe there are some bugs with LLaVA like [https://github.com/haotian-liu/LLaVA/issues/1570](url). The discovery of internal confidence is very interesting and I want to try its zero-shot segmentation ability.

**Comment by anishk23733** [comment]
Do you know if the error occurs during LLaVA inference or the logit lens calculation process (in our code)? If it is the former, it might be related to the LLaVA bug you sent. Could you provide a stack trace of the error?

**Comment by zhengyuan-xie** [comment]
Traceback (most recent call last):
  File "/defaultShare/archive/xiezhengyuan/vl-interp/demos/internal_confidence.py", line 31, in <module>
    caption, softmax_probs = retrieve_logit_lens(model_state, img_path)
  File "/defaultShare/archive/xiezhengyuan/vl-interp/methods/llava_utils.py", line 146, in retrieve_logit_lens_llava
    logit_scores = logits_warper(input_ids, logit_scores_processed)
  File "/opt/conda/envs/vl/lib/python3.9/site-packages/transformers/generation/logits_process.py", line 510, in __call__
    indices_to_remove = scores < torch.topk(scores, top_k)[0][..., -1, None]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.06 GiB. GPU 0 has a total capacty of 23.69 GiB of which 1.31 GiB is free. Process 1112174 has 22.38 GiB memory in use. Of the allocated memory 20.77 GiB is allocated by PyTorch, and 1.29 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by anishk23733** [comment]
@zhengyuan-xie just pushed a change to retrieve the logit lens values on the CPU instead—I believe this was causing the OOM error! Let me know if it works for you now.

**Comment by zhengyuan-xie** [comment]
> @zhengyuan-xie just pushed a change to retrieve the logit lens values on the CPU instead—I believe this was causing the OOM error! Let me know if it works for you now.

It works for me. Many thanks for all the help!

**Comment by anishk23733** [comment]
Perfect, closing the issue 🙂
